feat: discord notifier on failed tests (#5)

diff --git a/.github/workflows/run-test-every-hour.yml b/.github/workflows/run-test-every-hour.yml
--- a/.github/workflows/run-test-every-hour.yml
+++ b/.github/workflows/run-test-every-hour.yml
@@ -4,16 +4,22 @@ on:
   - cron: "0 * * * *"
 
 jobs:
-  build:
+  e2e-tests:
     name: Run TestCafe Tests
     runs-on: ${{ matrix.os }}
+    outputs:
+      outputreport: ${{ steps.testreport.outputs.report }}
+      status: ${{ steps.testreport.outputs.status}}
     strategy:
       matrix:
-        os: [windows-latest]
+        os: [ubuntu-latest]
         node: [14]
     env:
       E2E_URL: 'https://dev.akord.link'
     steps:
+      - uses: browser-actions/setup-chrome@v1
+        with:
+          chrome-version: latest
       - uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node }}
@@ -21,4 +27,33 @@ jobs:
       - name: Install dependencies
         run: npm install
       - name: Run TestCafe
-        run: npm run e2e
+        run: npm run e2e:headless
+      - id: testreport
+        name: Echo report
+        run: |
+          report_json=$(jq -c . dist/e2e/test-results.json)
+          passed=$(echo "$report_json" | jq -r '.passed')
+          total=$(echo "$report_json" | jq -r '.total')
+          skipped=$(echo "$report_json" | jq -r '.skipped')
+          parsed_report="FrontEnd Tests: Passed $passed/$total ($skipped skipped)" 
+          echo $parsed_report
+          echo "report=$parsed_report" >> "$GITHUB_OUTPUT"
+
+          if [ $((passed + skipped)) == $total ]; then
+            echo "Tests passed!"
+          else
+            echo "Tests failed!"
+            exit 1
+          fi
+
+  send-discord-notification:
+    needs: e2e-tests
+    runs-on: ubuntu-latest
+    if: ${{ failure() }}
+
+    steps:
+      - name: Notify Discord on job status
+        uses: tsickert/discord-webhook@v5.3.0
+        with:
+          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
+          content: "${{needs.e2e-tests.outputs.outputreport}}"
